config/routes.rb
Social::Application.routes.draw do

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users do
    resources :businesses, :except => [:index,:show] do
      resources :scheduled_posts, :except => [:new,:index,:show]
    end
    collection do
          get 'change_password'
          put 'update_password'
      end
  end
  resources :contact_us,:only=>[:new,:create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets,:only => [:new,:create,:edit,:update]
  
  match "/signup" => "users#new", as: :signup
  match "/login" => "sessions#new", as: :login
  match "/logout" => "sessions#destroy", as: :logout
  match "/delayed_job" => DelayedJobWeb, :anchor => false
  match 'contact' => 'contact_us#new',:as=>:contact
  
  match "/comingsoon" => "static_pages#comingsoon", as: :comingsoon
  match "/toc" => "static_pages#toc", as: :toc
  match "/about" => "static_pages#about", as: :about
  match "/faq" => "static_pages#faq", as: :faq
  match "/privacy_policy" => "static_pages#privacy", as: :privacy

  match "users/:user_id/businesses/:id/social_profile" => "businesses#social_profile", as: :social_profile
  match "users/:user_id/social_accounts" => "users#social_accounts", as: :social_accounts
  match "users/:user_id/businesses/:id/remove_twitter" => "businesses#remove_twitter", as: :twitter_removal
  match "users/:user_id/businesses/:id/remove_facebook" => "businesses#remove_facebook", as: :facebook_removal
  match "/auth/twitter/callback" => "businesses#twitter_callback"
  match "/auth/facebook/callback" => "users#facebook_callback"
  match "users/:user_id/businesses/:id/dashboard" => "content#index", as: :business_dashboard
  match "users/:user_id/businesses/:id/scheduled" => "content#scheduled_posts", as: :scheduled_posts
  
  match "users/:user_id/businesses/:id/textual" => "content#textual", as: :textual_post

  match "users/:user_id/businesses/:id/textual/post_now" => "content#post_now", as: :post_now
  match "users/:user_id/businesses/:id/textual/post_image_now" => "content#post_image_now", as: :post_image_now

  match "users/:user_id/businesses/:id/images" => "content#images", as: :image_post
  match "users/:user_id/businesses/:id/videos" => "content#videos", as: :video_post
  
  root to: "static_pages#home"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :username, :post_times_attributes,:country,:dob,:timezone,:old_password,:name
  attr_accessor :password,:remember_me,:old_password,:password_confirmation,:update_password
  has_secure_password
  
  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, format: { with: valid_email_regex }
  validates :email, uniqueness: true
  validates :password, length: { within: 6..50 }, on: :create
  
  before_save :create_remember_token
  after_create :welcome_mail

  # associations
  has_many :businesses, dependent: :destroy
  has_many :facebook_pages, dependent: :destroy
  
  def to_param
    "#{id}-#{username.gsub(/[^a-z0-9]+/i, '-')}"
  end

  def welcome_mail
    UserMailer.welcome_message(self).deliver      
  end

  # Encrypts the password into the password_digest attribute.
  def password=(unencrypted_password)
    @password = unencrypted_password
    unless unencrypted_password.blank?
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def send_password_reset
    self.password_reset_token = SecureRandom.urlsafe_base64
    self.password_reset_sent_at = Time.now
    self.save!
    UserMailer.password_reset(self).deliver
  end

  
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

    def old_password_match
    expected_password = User.encrypted_password(old_password, self.password_digest)
    if self.hashed_password != expected_password
      errors.add(:base,"Old Password is invalid.")
      return false
    else
      return true
    end
  end

  handle_asynchronously :welcome_mail, :priority => 1
      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, :only => ['show']
  before_filter :correct_user, :only => ['show','edit','update','change_password','update_password','destroy']
  
  # GET /users/1
  # GET /users/1.json
  def show
    @businesses = @user.businesses
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save       
        format.html do
          sign_in @user
          flash[:notice] = "Welcome to SocialApp!"
          #UserMailer.welcome_message(@user).deliver
          redirect_to @user
        end
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
   
  end

  def update
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html do
          sign_in @user
          flash[:notice] = "Your profile was updated successfully"
          redirect_to @user
        end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  def change_password   
  end

  def update_password
     if params[:user][:password] == params[:user][:old_password]
      @user.update_attribute(:password,params[:user][:password])
       flash[:notice] = 'Password updated successfully.'
       redirect_to :controller => "users",:action => "edit",:id => @user.id
     else
        flash[:notice] = 'Password does not match.'
        redirect_to :controller => "users",:action => "edit",:id => @user.id
     end
  end

  def facebook_callback
    auth = request.env["omniauth.auth"]

    me = FbGraph::User.me(auth["credentials"]["token"])

    me.accounts.each do |account|
      @page = FacebookPage.new
      @page.user_id = current_user.id
      @page.facebook_uid = auth["uid"]
      @page.facebook_page_access_token = account.access_token
      @page.facebook_page_id = account.identifier
      @page.facebook_page_name = account.name
      @page.save
    end
    flash[:notice] = "Facebook account added successfully."
    redirect_to root_path
  end

  def social_accounts
  end


    private
    def correct_user
        @user = User.find_by_id(params[:id])
        redirect_to root_path unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_businesses.html.erb
<section class="row content">
<div class="twelve column clearfix">
  <% if businesses.any? %>
        <% businesses.each do |business| %>
        <div class="busprofile">
            <div class="bushead">
                <div class="showlogo">                   
                    <%= link_to image_tag(business.photo.url(:thumb)),scheduled_posts_path(@user, business) %>
                </div>
                <h1><a href="<%= scheduled_posts_path(@user, business) %>"><%= business.business_name %></a></h1>
                <!--<h5 ><%#= business.description %></h5>-->
                <ul class="connectedservices">
                    <% if business.facebook_page_id.blank? %>
                        <a href="<%= social_profile_path(current_user, business)%>" title = "facebook page not connected">
                            <li class="facebookconnect_hover" >Facebook</li>
                        </a>  
                    <% else %>
                        <a href="<%= social_profile_path(current_user, business)%>" title = "facebook page connected">
                            <li class="facebookconnect">Facebook</li>
                        </a>  
                    <% end %>    

                    <% if business.twitter_token.blank? %>
                        <a href="<%= social_profile_path(current_user, business)%>" title = "twitter page not connected">
                            <li class="twitterconnect_hover">Twitter</li>   
                        </a>    
                    <% else %>
                        <a href="<%= social_profile_path(current_user, business)%>" title = "twitter page connected">
                            <li class="twitterconnect">Twitter</li>
                        </a>    
                    <% end %>  
                </ul>
            	<%= link_to "Manage", scheduled_posts_path(@user, business), class: "button nice small white radius cornerbtn" %>
        	</div>
        	
            <div class="content_list clearfix dashpad"> 
                <% @business = business.scheduled_posts.find(:all,:conditions => ['archived =? and publish_date >?',false,Time.now + Time.zone_offset(Time.now.zone)],:order => "publish_date") %>  
                <% if @business.count != 0 %>             
                    <% @business.each_with_index do |schedule_post,index| %>
                        <div class="textual">
                            <div class="box" id = "box_<%= schedule_post.id %>">
                                <%= link_to 'x', [@user, business, schedule_post], confirm: "Are you sure", method: :delete, class: "delete_button",:title => "Delete this Post" %>
                                <span class="label white time"><%= schedule_post.publish_date.strftime("%d-%m-%y %H:%M") %></span>
                            
                                <% if schedule_post.post_type == "text" %>
                                    <h3><%= link_to schedule_post.title, schedule_post.link,:class => "post_link", :target => "_blank"%></h3>
                                    <p class="snippet"><%= schedule_post.content %></p>
                                <% else %>    
                                    <div class="img_wrap">
                                        <%= image_tag schedule_post.thumbnail_url, class: "thumbnail" %>
                                    </div>
                                    <a href="<%= schedule_post.link %>", class="post_link", target="_blank"><h6><%= schedule_post.title %></h6></a>
                                <% end %>
                            
                                <%= link_to "Edit", edit_user_business_scheduled_post_path(@user, business, schedule_post), class: "small button white nice centered schedule_post edit_scheduled_post radius" %>

                                <%= link_to_function ' ', "mark_as_archived(#{schedule_post.id})",:id => "archived_#{schedule_post.id}" , :class => "archive",:title => "Post and Archive" %><br>
                           
                                <% if schedule_post.starred == false %>
                                    <%= link_to_function '', "mark_as_starred(#{schedule_post.id})",:id => "starred_#{schedule_post.id}",:class=>"small_star",:title => "Mark as Starred" %><br>
                                
                                <% else %>
                                    <%= link_to_function '', "mark_as_starred(#{schedule_post.id})",:id => "starred_#{schedule_post.id}",:class=>"small_star_active",:title => "Remove from Starred" %>
                                <% end %>
                            </div><!--box-->
                        </div><!--textual-->
                        <%#= index%>

                        <div class="reveal-modal" id = "edit_post_<%= schedule_post.id%>">
                        
                        </div>   

                        <% break if index == 3 %>
                    <% end %> 
                
                <% else %>
                    <h4><i style = "color:#666;">No post is scheduled.</i><h4/>
                <% end %>   
            </div>
        	
        </div>    
        <% end %>
      <% end %>
    </div>
</section>

app/views/users/_edit_form.html.erb
   <h3>Edit your profile</h3>
  <%= form_for(@user, html: { class: "nice clearfix" }) do |f| %>
    
    <%= render "shared/error_messages", object: f.object %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class: "large input-text", placeholder: "John" %>
    </div>

    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username, class: "large input-text" %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email, class: "input-text large", placeholder: "john@doe.com" %>
    </div>

    <div class="field" >
      <%= f.label :dob, "Date of Birth" %>
      <%= f.date_select :dob, :start_year => 1950, :order => [:day, :month, :year] %>
    </div>

    <div class="">
      <%= f.label :country %>
      <%= country_select "user", "country" , nil, {}, {:class => 'select_width'} %>
    </div>

    <div class="field">
      <%= f.label :timezone %>
      <%= f.time_zone_select :timezone , nil, {}, {:class => 'select_width'}%>
    </div>
 
    <div class='field'>
        <%= f.label :password, 'Password' %>
        <%= link_to "Change Password",{:controller => 'users',:action => 'change_password',:id=> @user.id }, :class=>'button medium rounded white'%>
    </div>

    <div class="action">
      <%= f.submit "Update profile", class: "button blue medium nice themebutton large center radius" %>
    </div>
  <% end %>

app/views/users/_form.html.erb
  <%= form_for(@user, html: { class: "nice clearfix" }) do |f| %>
    
    <h3>Signup<span class="subhead"><%= link_to "Already have an account? Login now.", login_path %></span></h3>
    <%= render "shared/error_messages", object: f.object %>
    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username, class: "large input-text", placeholder: "John" %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email, class: "input-text large", placeholder: "john@doe.com" %>
    </div>
  
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password, class: "input-text large", placeholder: "Secret password" %>
    </div>
  
    <div class="field">
      <%= f.label :password_confirmation, "Please enter your password again." %>
      <%= f.password_field :password_confirmation, class: "input-text large", placeholder: "Secret password" %>
    </div>
  
    
    <div class="action">
      <%= f.submit "Signup", class: "button blue medium themebutton nice large left radius" %>
    </div>
  <% end %>

app/views/users/edit.html.erb
<% content_for :title, "Edit Profile" %>
<section class="small_box container  edit_user_page">
  <div class="row">
    <div class="box seven columns theform centered">
      <%= render 'edit_form' %>
    </div><!--six columns-->
  </div><!--row-->
</section><!--container-->

app/views/users/new.html.erb
<% content_for :title, "SignUp with SocialGator" %>
<section class="small_box container">
  <div class="row">
    <div class="box seven theform columns centered">
      <%= render 'form' %>
    </div><!--six columns-->
  </div><!--row-->
</section><!--container-->

app/views/users/show.html.erb
<% content_for :title, "Curated Content To Manage Your Social Media Profile" %>
<section class="subheadwrap">
 	<div class="subhead">
      	<h3><span class="bolder"><%= @user.username %></span>, your scheduled posts are listed below.</h3>
      	<div class="panelnav">
            <% if @user.facebook_pages.blank? %>
                <%= link_to "+  Add Business", social_accounts_path(@user), class: "button small white nice radius right" %>
            <% else %>
                <%= link_to "+  Add Business", new_user_business_path(@user), class: "button small white nice radius right" %>
            <% end %>
      	</div>
  	</div><!--row-->
</section><!--user container-->

<%= render 'businesses', :businesses => @businesses %>
 
<script>
function mark_as_starred(schedule_post_id)
{
  $.ajax( 
    { 
      dataType: "json", 
      cache: false, 
      type: 'post', 
      url: '/scheduled_posts/mark_as_starred?id='+schedule_post_id, 
      success: function(data) 
      { 
        if(data.name == "true")
        { 
          $("#starred_"+schedule_post_id).removeClass('small_star').addClass('small_star_active');
          $("#notice").show();
          $('#notice').html("This post has been starred.").delay(5000).fadeOut(500);
          
        }
        else if(data.name == "false")
        { 
          $("#starred_"+schedule_post_id).removeClass('small_star_active').addClass('small_star');
          $("#notice").show();
          $('#notice').html("This post has been unstarred.").delay(5000).fadeOut(500);
          
        }
      } 
    });
}

function mark_as_archived(schedule_post_id)
{
  $.ajax( 
    { 
      dataType: "json", 
      cache: false, 
      type: 'post', 
      url: '/scheduled_posts/mark_as_archived?id='+schedule_post_id, 
      success: function(data) 
      { 
        if(data.name == "true")
        { 
          $("#box_"+schedule_post_id).hide();
          $("#notice").show();
          $('#notice').html("This post has been archived.").delay(5000).fadeOut(500);
          
        }
      } 
    });
}
</script>

app/views/users/social_accounts.html.erb
<% content_for :title, "Social Profile" %>
<section class="small_box container add_business">
  <div class="row">
    <div class="box five columns centered">
        <h3>Add your social profile first</h3>
      	<div class="field addfacebookpage_paddingleft">
          <%= link_to "Add Facebook Account", "/auth/facebook", class: "centered facebookadd" %>
  		</div>
  
    </div><!--six columns-->
  </div>

  <div class="row">
    <div class="three columns centered">
      <%= link_to "Go back to your profile.", user_path(current_user), class: "button nice  medium themebutton radius" %>
    </div>
  </div>
  </div><!--row-->
</section><!--container-->