config/routes.rb
Social::Application.routes.draw do

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users do
    resources :businesses, :except => [:index,:show] do
      resources :scheduled_posts, :except => [:new,:index,:show]
    end
    collection do
          get 'change_password'
          put 'update_password'
      end
  end
  resources :contact_us,:only=>[:new,:create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets,:only => [:new,:create,:edit,:update]
  
  match "/signup" => "users#new", as: :signup
  match "/login" => "sessions#new", as: :login
  match "/logout" => "sessions#destroy", as: :logout
  match "/delayed_job" => DelayedJobWeb, :anchor => false
  match 'contact' => 'contact_us#new',:as=>:contact
  
  match "/comingsoon" => "static_pages#comingsoon", as: :comingsoon
  match "/toc" => "static_pages#toc", as: :toc
  match "/about" => "static_pages#about", as: :about
  match "/faq" => "static_pages#faq", as: :faq
  match "/privacy_policy" => "static_pages#privacy", as: :privacy

  match "users/:user_id/businesses/:id/social_profile" => "businesses#social_profile", as: :social_profile
  match "users/:user_id/social_accounts" => "users#social_accounts", as: :social_accounts
  match "users/:user_id/businesses/:id/remove_twitter" => "businesses#remove_twitter", as: :twitter_removal
  match "users/:user_id/businesses/:id/remove_facebook" => "businesses#remove_facebook", as: :facebook_removal
  match "/auth/twitter/callback" => "businesses#twitter_callback"
  match "/auth/facebook/callback" => "users#facebook_callback"
  match "users/:user_id/businesses/:id/dashboard" => "content#index", as: :business_dashboard
  match "users/:user_id/businesses/:id/scheduled" => "content#scheduled_posts", as: :scheduled_posts
  
  match "users/:user_id/businesses/:id/textual" => "content#textual", as: :textual_post

  match "users/:user_id/businesses/:id/textual/post_now" => "content#post_now", as: :post_now
  match "users/:user_id/businesses/:id/textual/post_image_now" => "content#post_image_now", as: :post_image_now

  match "users/:user_id/businesses/:id/images" => "content#images", as: :image_post
  match "users/:user_id/businesses/:id/videos" => "content#videos", as: :video_post
  
  root to: "static_pages#home"

  match ':controller(/:action(/:id))(.:format)'
end

app/views/shared/_content_page_header.html.erb
<div id="business_modal" class="reveal-modal">
  <h2>Switch businesses profile</h2>
  <% if @user.businesses.any? %>
    <ul class="switch_business_list">
      <% @user.businesses.each do |business| %>
        <li>
        <%= link_to (image_tag(business.photo.url(:medium), class:'chooseimage') + business.business_name + "<span class='thin'>( Facebook, Twitter )</span>".html_safe), textual_post_path(@user, business) %></li>
      <% end %>
    </ul>
  <% end %>
  <a class="close-reveal-modal">&#215;</a>
</div><!--modal-->

<div class="container current_business sectionpanel">
  <div class="row">
    <div class="wrapper twelve columns">
      <div class="twelve columns">
      		<div class="logowrap">
                <%= image_tag(@business.photo.url(:medium))%>
      		</div>
        	<h5 class="businessname"><%= @business.business_name %></h5>
        	<ul class="connectedservices">
            <% if @business.facebook_page_id.blank? %>
                <a href="<%= social_profile_path(current_user, @business)%>" title = "facebook page not connected">
                  <li class="facebookconnect_hover" >Facebook</li>
                </a>  
            <% else %>
                <a href="<%= social_profile_path(current_user, @business)%>" title = "facebook page connected">
                  <li class="facebookconnect">Facebook</li>
                </a>  
            <% end %>    

            <% if @business.twitter_token.blank? %>
        		<a href="<%= social_profile_path(current_user, @business)%>" title = "twitter page not connected">
                    <li class="twitterconnect_hover">Twitter</li>	
                </a>    
            <% else %>
                <a href="<%= social_profile_path(current_user, @business)%>" title = "twitter page connected">
                    <li class="twitterconnect">Twitter</li>
                </a>    
            <% end %>  

        	</ul>
        	<h6 class="keywords">
        	  <% if @business.keywords.any? %>
              <strong> Keywords : 
                <% @business.keywords.each do |k| %>
                  <span class='key'><%= k.token %></span>
                <% end %>
              </strong>
            <% end %></h6>
        </div>

        <div class="links panelnav clearfix">
          <%= link_to "Edit Business", edit_user_business_path(@user, @business), class: "button small white radius nice right" %>
        </div>
      </div><!--panel-->
      </div><!--wrapper-->
    </div><!--row-->
</div><!--container-->


<script>
  $(document).ready(function() {
    $('.show_content_modal').click(function() {
      $('#new_content_modal').reveal();
      return false;
    });
  });
</script>


<section class="container content">  
    <div class="content_box row">
      <dl class="nice contained tabs">
  			<%= nav_link "Scheduled", scheduled_posts_path(@user, @business) %>
  			<%= nav_link "Text", textual_post_path(@user, @business) %>
  			<%= nav_link "Images", image_post_path(@user, @business) %>
  			<%= nav_link "Videos", video_post_path(@user, @business) %>
  			<%= link_to "+ Add custom post", "#", class: "button nice right themebutton radius hide-on-mobiles show_content_modal "%>
      </dl>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error_explanation">
    <h4 class="error_heading"><%= pluralize(object.errors.count, 'error') %> prohibited this user from being saved.</h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>