config/routes.rb
Social::Application.routes.draw do

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :users do
    resources :businesses, :except => [:index,:show] do
      resources :scheduled_posts, :except => [:new,:index,:show]
    end
    collection do
          get 'change_password'
          put 'update_password'
      end
  end
  resources :contact_us,:only=>[:new,:create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets,:only => [:new,:create,:edit,:update]
  
  match "/signup" => "users#new", as: :signup
  match "/login" => "sessions#new", as: :login
  match "/logout" => "sessions#destroy", as: :logout
  match "/delayed_job" => DelayedJobWeb, :anchor => false
  match 'contact' => 'contact_us#new',:as=>:contact
  
  match "/comingsoon" => "static_pages#comingsoon", as: :comingsoon
  match "/toc" => "static_pages#toc", as: :toc
  match "/about" => "static_pages#about", as: :about
  match "/faq" => "static_pages#faq", as: :faq
  match "/privacy_policy" => "static_pages#privacy", as: :privacy

  match "users/:user_id/businesses/:id/social_profile" => "businesses#social_profile", as: :social_profile
  match "users/:user_id/social_accounts" => "users#social_accounts", as: :social_accounts
  match "users/:user_id/businesses/:id/remove_twitter" => "businesses#remove_twitter", as: :twitter_removal
  match "users/:user_id/businesses/:id/remove_facebook" => "businesses#remove_facebook", as: :facebook_removal
  match "/auth/twitter/callback" => "businesses#twitter_callback"
  match "/auth/facebook/callback" => "users#facebook_callback"
  match "users/:user_id/businesses/:id/dashboard" => "content#index", as: :business_dashboard
  match "users/:user_id/businesses/:id/scheduled" => "content#scheduled_posts", as: :scheduled_posts
  
  match "users/:user_id/businesses/:id/textual" => "content#textual", as: :textual_post

  match "users/:user_id/businesses/:id/textual/post_now" => "content#post_now", as: :post_now
  match "users/:user_id/businesses/:id/textual/post_image_now" => "content#post_image_now", as: :post_image_now

  match "users/:user_id/businesses/:id/images" => "content#images", as: :image_post
  match "users/:user_id/businesses/:id/videos" => "content#videos", as: :video_post
  
  root to: "static_pages#home"

  match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_footer.html.erb
<footer class="container main_footer">
    <div class="row">
      <div class="columns">
        <ul>
          <li class="heading"><strong>SocialGator</strong></li>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "FAQs", faq_path %></li>
          <li><%= link_to "Contact Us", contact_path %></li>
        </ul>
      </div><!--two columns-->
      
      <div class="columns">
        <ul>
          <li class="heading"><strong>Links</strong></li>
          <li><%= link_to "Terms", toc_path %></li>
          <li><%= link_to "Privacy", privacy_path %></li>
          <li><%= link_to "Disclaimer", "#" %></li>
        </ul>
      </div><!--two columns-->
      
      <div class="columns">
        <ul>
          <li class="heading"><strong>Social</strong></li>      
          <li><%= link_to "Facebook", "#" %></li>
          <li><%= link_to "Twitter", "#" %></li>
          <li><%= link_to "Google Plus", "#" %></li>
        </ul>
      </div><!--two columns-->
      
      <div class="three columns offset-by-three">
        <%= link_to image_tag("fizzy_logo.png"), "http://www.fizzysoftware.com",:target => "_blank" %>
      </div><!--two columns-->    
    </div><!--row-->
</footer><!--footer-->

app/views/layouts/_header.html.erb
<header class="container top_bar">  
    <div class="row">
        <a href="<%= root_path %>" id="logo" class="two columns left"><h1 class="sitelogo">SocialGator</h1></a>
      
        <% if signed_in? %>
            <ul class="left nav-bar hide-on-mobiles">
                <li><%= link_to "Publish", user_path(current_user), class: "main margin_left" %></li>
                <li><%#= link_to "Build", comingsoon_path, class: "main" %></li>
                <li><%#= link_to "Analytics", comingsoon_path, class: "main" %></li>
            </ul><!--right-->
        <% end %>
      
        <ul class="right nav-bar hide-on-mobiles">
            <% unless signed_in? %>
            <li><%= link_to "Login", login_path, class: "main" %></li>
            <li><%= link_to "Signup", signup_path, class: "main light" %></li>
        </ul><!--right-->
        
            <% else %>
                <% unless controller.controller_name == "businesses" %>
                    <% if current_user.businesses.any? %>
                        <li class="has-flyout">
                            <a href="#" class="main">Businesses</a>
                            <a href="#" class="flyout-toggle"><span></span></a>
                            <div class="flyout">
                                <ul class="actions">
                                    <% current_user.businesses.each do |business| %>
                                        <li><%= link_to business.business_name, scheduled_posts_path(current_user, business), class: "" %></li>
                                    <% end %>
                                    <li><%= link_to "+ Add Business", new_user_business_path(current_user), class: "" %></li>
                                </ul>
                            </div>
                        </li>

                    <% end %>
            <% end %>

            <li class="has-flyout">
                <%= link_to current_user.username.humanize, user_path(current_user), class: "main" %>
                <a href="#" class="flyout-toggle"><span></span></a>
                <div class="flyout">
                    <ul class="actions">
                        <li><%= link_to "Edit Profile", edit_user_path(current_user), class: "" %></li>
                        <li><%= link_to "Logout", logout_path, class: "" %></li>
                    </ul>
                </div>
            </li>
        </ul><!--right-->
      <% end %>
    </div><!--row-->

    <div class ="fork">
        <%= link_to image_tag('fork.png'),  'https://github.com/fizzysoftware/SocialGator',:target => '_blank' %>
    </div>
</header><!--top-bar-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" type="image/x-icon" href="/assets/favicon.ico">
  <title>SocialGator | <%=h yield(:title) || "Curated Content To Manage Your Social Media Profile" %></title>
    <meta name="author" content="FizzySoftware" />
	<meta name="keywords" content="social media, twitter, facebook, curated content, manage profile, manage social media accounts, social media analysis">
	<meta name="description" content="SocialGator provides you with curated content to manage, engage and analyze your social media profiles.">
	
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:600,400,700' rel='stylesheet' type='text/css'>
  
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "screen" %>
</head>
<body>
  <div id='notice' style="<%= 'display: none; ' if flash[:notice].blank? %> text-align: center;"><%= flash[:notice].html_safe  unless flash[:notice].blank? %></div>
 
  <div id='error' style="<%= 'display: none;' if flash[:error].blank? %>  text-align: center;"><%= flash[:error].html_safe  unless flash[:error].blank? %></div>

  <%= render 'layouts/header'%>
  
  <%= yield %>

  <%= render 'layouts/footer'%>

</body>
<script>
$(function(){
  $('#notice').delay(3000).slideUp(200);
  $('#error').delay(3000).slideUp(200);
});
</script>
</html>